### ISSUE TITLE
(Req) save-data mounting patches

### ISSUE THREAD

**Issue by bucanero** [GoldHEN/GoldHEN#1]
Hi @SiSTR0 , could it be possible to include the save-data mounting patches in a future version of GoldHen?

I'm referring to these patches that allow an app or homebrew to mount any save-games:
https://github.com/xXxTheDarkprogramerxXx/ps4-hen-vtx/blob/master/kpayload/source/patch.c#L248

thanks for all your work! 👍

**Comment by SiSTR0** [comment]
I don't think they are enough to achieve your goals. but as soon as you have something ready let's try to find a solution 😉
