### ISSUE TITLE
[Update Request] New Goldhen Updates for 7.55

### ISSUE THREAD

**Issue by Kinho-Loureiro** [GoldHEN/GoldHEN#103]
Hi Sistro! Congratulations for your job with Goldhen dude.

I wanna request to update the new features for the old 7.xx/7.55 FWs. Why is only 9.00 FW?? Is it possible?

 I've waiting so long for this updates and I can keep my Ps4 on this firmware because I have faith in the permanent Hen or maybe a PS4 CFW in some day. 🙏🙏🙏

**Comment by IRONB0SS** [comment]
> Hi Sistro! Congratulations for your job with Goldhen dude.
> 
> I wanna request to update the new features for the old 7.xx/7.55 FWs. Why is only 9.00 FW?? Is it possible?
> 
>  I've waiting so long for this updates and I can keep my Ps4 on this firmware because I have faith in the permanent Hen or maybe a PS4 CFW in some day. 🙏🙏🙏 

Dude 7.55 is very unstable, please update fw to 9.00
It really worth

**Comment by Kinho-Loureiro** [comment]
> but dude for the wrost act for me on 9.00 is the exfat usb drive required for boot hen enable and the possibility of Nand Crash. I realy aprecciate my Jailbreak PS4 Slim and lose her its so terrible😫

**Comment by kmeps4** [comment]
I'll close this one since this is not a bug.. it's a request.
Will close it as no planned.
