### ISSUE TITLE
[REQUEST] ESP8266 Auto mount USB GoldHEN v2.3

### ISSUE THREAD

**Issue by francoataffarel** [GoldHEN/GoldHEN#105]
Hello sir can u release ESP8266 Auto mount USB GoldHEN v2.3?

being more specific can you update this folder on mega?

\/

https://mega.nz/folder/MHJCxLbJ#ilX7UeOlldGJpAzPaazreA/folder/BeRmiTzT

**Comment by kmeps4** [comment]
ESP8266 builds are not related to GoldHEN payloads.
Will close as not planned.

**Comment by francoataffarel** [comment]
🇮🇹

Em ter, 3 de jan de 2023 16:04, Kameleon ***@***.***>
escreveu:
