### ISSUE TITLE
[REQUEST] Goldhen 2.3 for 7.55 FW - Please🙏

### ISSUE THREAD

**Issue by Kinho-Loureiro** [GoldHEN/GoldHEN#107]
Man we need this new features on old FWs, port for then please🙏🙏🙏
We locked on 2.2.2 and can not use this new upgrades like FPS, Plugins, Internal Pkg Install. We need this too.😫

**Comment by kmeps4** [comment]
I'll close this one since this is not a bug.. it's a request.
Will close it as no planned.
