### ISSUE TITLE
[Debug Logger] Binloader doesn't load any payload until...

### ISSUE THREAD

**Issue by VirusBurst** [GoldHEN/GoldHEN#109]
I have currently the PS4 Slim running 9.00 w/ latest Stooged ESP32 Server and I usually load my payload via PayloadGuest from Al-Azif 0.98

Recently it happens more and more, that none of my payload get loaded ALTHOUGH the binloader replies with "Payload received from"
either from Windows, Website or App...

Sometimes the issue is fixxed with restarting the binloader or even rebooting the console. Sometimes, if get stuck forever until a miracle happens (like today... LinuxLoader finally works.... again... until NVM)

So I'd like to ask, whether I can monitor the binloader to check, what actually happens behind the scenes and whether maybe something unusual happens...

**Comment by Francesco146** [comment]
yes, Mine is stuck. does anyone know a workaround?

**Comment by Francesco146** [comment]
i didn't test the new release, v2.4.16.2, I'll test it next week and update this comment. :)

**Comment by SiSTR0** [comment]
Check new binloader on v2.4b18+
