### ISSUE TITLE
Can we get the ability to transfer to an installed usb drive?

### ISSUE THREAD

**Issue by steve51184** [GoldHEN/GoldHEN#110]
"Internal pkg installation support (/data/pkg)"

Is amazing but can we get usb support? Like /mnt/usb0/data/pkg then I can install from package installer like normal but from usb etc

**Comment by KrisztianKende** [comment]
USB support is already there, but the pkg files need to be placed in the root of the partition. If you need to install a pkg from a subdirectory, use PS4-Xplorer.

**Comment by SiSTR0** [comment]
This feature was added in latest version, try v2.4b18
