### ISSUE TITLE
FTP/syslog servers stop working after network settings change

### ISSUE THREAD

**Issue by InvoxiPlayGames** [GoldHEN/GoldHEN#111]
Firmware: 9.00

When changing the system's internet settings with GoldHEN loaded, the FTP (21) and syslog (3232) servers stop working - they still accept new connections, but no data is received on the computer side. Putting the system into rest mode and waking it back up resolves the issue.

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18
