### ISSUE TITLE
[REQUEST] Support folders in '/data/pkg' directory

### ISSUE THREAD

**Issue by Neipas09** [GoldHEN/GoldHEN#113]
Not sure if it's possible, but add support for folders in the /data/pkg folder
It would be nice if i can just drag&drop a game folder into the pkg folder, and it reads all the pkg files in the game folder.

**Comment by SiSTR0** [comment]
Internal HDD /data/pkg support was ton v2.3 and higher

**Comment by Neipas09** [comment]
That's not what i asked.
I'm asking for FOLDER support in /data/pkg
