### ISSUE TITLE
mc4 files aren't recognized in the Cheat Menu

### ISSUE THREAD

**Issue by RedShifter1** [GoldHEN/GoldHEN#116]
I've only been able to verify on a handful of games, but of those games all of the ones that only have mc4 files will recognize the game as matching in the separate Cheat Manager app, but not in the actual GoldHEN Cheat Menu.

**Comment by rambooo9000** [comment]
I'm using goldhen 2.3, I don't see it either.

**Comment by TimMods** [comment]
Same here on 2.3 / 5.05
They did work on the beta versions.

**Comment by SiSTR0** [comment]
Support for mc4 has been officially added in version 2.3
