### ISSUE TITLE
Cheat Menu Crashes

### ISSUE THREAD

**Issue by RedShifter1** [GoldHEN/GoldHEN#122]
When I try to launch the cheat menu, both during gameplay and on the home screen options menu, for Snowrunner it freezes and then crashes. It doesn't do a full crash where I need to restart the PS4, it just freezes and then usually exits to the game (still frozen) for a few seconds before closing out into the main screen. Interestingly the game is only suspended and you can immediately reopen it without any problems. It has trainers for it so I know that someone along the way has been able to make it work but I have no idea how to troubleshoot this to find a solution. Help please? I could use some guidance, I would really like to access the cheats for this game.

**Comment by djender985** [comment]
I have this issue as well.

**Comment by rambooo9000** [comment]
the game must be the same example cusa20201 v1.00 if the json should all be the same then there may be an error in the cheat codes or the eboot.bin may be different this is the reason for the ps4 crash

**Comment by otorre1** [comment]
> I know this is old but not sure if it has been fixed because this is the first time I have ran into this problem.
> 
> I am on the latest version of GoldHen (v2.3 stable not v2.4b14 beta) and have GoldHen Cheats Manager installed and it is on the latest version with the latest updates for cheats and patches.
> 
> But when I try open the GoldHen Cheats Menu my console will completely freeze forcing me to power it off.
> 
> This will happen if I double press the PS button (which it has been set to) and if I hit PS button to go to the PS4 main screen and press Options then GoldHen Cheats Menu.
> 
> This is the only time I have noticed this and the game I am running is Cyberpunk 2027 (CUSA16596 v1.61), wondering if it be a problem with one of the cheat files causing the problem, I connect to my GoldHen Cheats Directory via FTP and delete all cheat files for the game from its JSON/MC4/SHN directories so there are no cheats at all for the game.
> 
> But it still crashes when ever I try bring up the GoldHen Cheat Menu rather than showing the screen saying there are no cheats for this game.

Same problem here
If I try 10 times, at least 6 freezes

**Comment by Retroboy85** [comment]
Thanks to help from Pharaoh2k, managed to pinpoint the cause of the problem (for me)

It was the patches folder, after renaming it so no patches could work, the crash issue was fixed.

**Comment by ricbermo** [comment]
@Retroboy85 would u mind explaining how to to that? I'm getting the same issue and I'm thinking is also related to the patches, since I had enabled one of them and now I'm getting such crashes.
