### ISSUE TITLE
PSVR

### ISSUE THREAD

**Issue by RedShifter1** [GoldHEN/GoldHEN#123]
I just got a PSVR2 and it worked until I loaded GoldHEN 2.3. Then it seemed to go incredibly zoomed in and unusable. Is this an existing issue with a known workaround? I can't find any info about VR and the jailbreak except that the FAQ for GoldHEN 2.3 says it supports it. I would really really appreciate some help and guidance. Thank you.

**Comment by EchoStretch** [comment]
PSVR2 Is for PS5 Only. If you wish to use psvr function, you will need to buy a psvr original.
