### ISSUE TITLE
Problema con add content manager

### ISSUE THREAD

**Issue by bombardeo38** [GoldHEN/GoldHEN#127]
Perdona tengo mi ps4 en 9.00 con unos 64 juegos instalados en el disco duro externo intento entar el debug settings para desins talar unas dlc y cada vez que entro en add content manager/delete me salta un error de software del sistema acabo de formatear la misma ps4 y con el mismo goldhen y con solo un juego si que me deja entrar será porque hay muchos juegos? gracias y disculpa

**Comment by Masamune3210** [comment]
Mi apuesta es que la unidad externa tiene alguna corrupción que está causando que el firmware se bloquee. Si tiene una unidad de repuesto, incluso una pequeña, intente configurarla como almacenamiento externo e intente recrear el problema.

**Comment by Masamune3210** [comment]
Sorry if its a bit rough to read, high school Spanish combined with google translate doesn't always end too well lol

**Comment by bombardeo38** [comment]
Gracias por la respuesta e comprobado la unidad y estoy volviendo a instalar los juegos y apps de momento si que puedo acceder al add content manager/delete solo e instalado 13 juegos de momento con las updates y sus dlc ya diré si se réplica el error
