### ISSUE TITLE
FW 6.72 Goldhen detected incorrect app version on many apps +0.01 from the actual version

### ISSUE THREAD

**Issue by Jatapong** [GoldHEN/GoldHEN#131]
Need help. I'm on FW 6.72 with Goldhen 2.4 beta 13. When running Goldhen cheat manager many games that available on my PS4 Pro wasn't detect by Goldhen because Goldhen detected wrong app version number.

- for example I have game & cheats database installed for Mega Man 11 / CUSA10738 v01.00 on my PS4 Pro. But when i enabled Showing Title ID & App Version in Goldhen it going to detected Mega Man 11 as version v01.01 (+0.01 from the actual version) but if i press start and check for the app version from home screen it showing v01.00 correctly

this issue occur to many apps on my PS4 or even older versions of Goldhen not help

**Comment by KrisztianKende** [comment]
Pkgs have two version numbers; Application Version and Master Version. GoldHEN shows the latter for merged pkgs. There is no way to detect if the base pkg is merged with the patch or not. So if the Master Version is higher than 01.00, it shows that.

**Comment by Masamune3210** [comment]
Yet another reason people should not be merging updates into the base. They are separate pkgs for a reason.
