### ISSUE TITLE
Help, All saves deleting bug

### ISSUE THREAD

**Issue by ToniFabri** [GoldHEN/GoldHEN#133]
I used the new Goldenhen save management option to see what it was and the ps4 crashed and then all game saves from all games were deleted!! and is it possible to recover these saves by pynton?

**Comment by Masamune3210** [comment]
No. Deleted means Deleted. What new save management options are you talking about.

**Comment by Masamune3210** [comment]
Also, what in the absolute heck possessed you to go randomly trying out things you don't fully understand?

**Comment by ToniFabri** [comment]
![PS4 6 72 5 05 Payload to Unlock Debug Features   FPKG Game Trophies](https://github.com/GoldHEN/GoldHEN/assets/68399025/71e3d07f-63e2-436a-93e3-075aa85ce4df)
but it was a menu option and not advanced, I remember that I went to delete the game too

**Comment by SiSTR0** [comment]
it is not a GoldHEN bug, try to don't check "Delete all users' saves" next time.

**Comment by Masamune3210** [comment]
If it has a star next to it, do not touch it unless you are absolutely sure what you are doing. Better yet, just don't touch things without understanding them first in general
> ![PS4 6 72 5 05 Payload to Unlock Debug Features FPKG Game Trophies](https://user-images.githubusercontent.com/68399025/252171921-71e3d07f-63e2-436a-93e3-075aa85ce4df.jpg) but it was a menu option and not advanced, I remember that I went to delete the game , but bug and deleting my saves

**Comment by ToniFabri** [comment]
> it is not a GoldHEN bug, try to don't check "Delete all users' saves" next time.

This image I got from the net, on my ps4 these options did not appear to mark, only the stars menu and when I clicked on saves the ps4 crashed, sure that everything was marked as automatic
