### ISSUE TITLE
FTP server in GoldHEN 2.4b14 causes Java's FTP client to hang

### ISSUE THREAD

**Issue by hippie68** [GoldHEN/GoldHEN#141]
I'm locked out of Discord, so I can't talk to Sistro the usual way. There's a bug in the FTP code that prevents some FTP clients - most notably Java's FTP implementation - from connecting properly. I hope you can forward this message to him so the bug gets fixed in GoldHEN 2.4, too. Thanks!
https://github.com/hippie68/ps4-ftp/commit/c903943d93dd082b590ee747c114a8c2436aaf71

**Comment by SiSTR0** [comment]
Great! thank you, will add in next version
