### ISSUE TITLE
Crash whan booting 

### ISSUE THREAD

**Issue by Bogdans29** [GoldHEN/GoldHEN#15]
Crash whan booting from rest mode the screen goes just blue like beckground blue whan selecting profiles.. 
And i found that only heppens ehan etharnet cable with Internet is pluged in and i also using al azif dns.. 
And just stays blue background 
Im on 9.0fw  GH2.02B

**Comment by Masamune3210** [comment]
Works fine for me, try reinitializing your system after backing things up

**Comment by Bogdans29** [comment]
> Works fine for me, try reinitializing your system after backing things up

Yeah  i forgot to menton it works day or two without problem but than its just metter of time..

**Comment by SiSTR0** [comment]
I did a new version in test with new injection method, contact me on OpenOrbis discord server to help me in other test

**Comment by Bogdans29** [comment]
> I did a new version in test with new injection method, contact me on OpenOrbis discord server to help me in other test
Do you have invite link

**Comment by SiSTR0** [comment]
try this https://discord.gg/GQr8ydn

**Comment by Pharaoh2k** [comment]
@SiSTR0 
I am occasionally having the same or a very similar issue when returning from rest mode, the screen stays blue and then after about a minute says there is an error with the system software or something similar.
When going to Settings - both GoldHen and Debug Settings are gone, but I can still run fpkgs without a problem.
The only way to fix this is to reboot and to JB again.

**Comment by SiSTR0** [comment]
Join on GoldHEN test server to test new version https://discord.gg/XG6F7MaH

**Comment by Pharaoh2k** [comment]
[**@SiSTR0**](https://github.com/SiSTR0) commented on [Jan 31, 2022, 1:09 AM GMT+7](https://github.com/GoldHEN/GoldHEN/issues/15#issuecomment-1025197829 "2022-01-30T18:09:22Z - Replied by Github Reply Comments"):
> Join on GoldHEN test server to test new version [https://discord.gg/XG6F7MaH](https://discord.gg/XG6F7MaH)

I am getting this error when trying to load the beta channel:
![KDPC5kB](https://user-images.githubusercontent.com/5753365/152093094-cc4a4a35-04c6-4fdd-a6b6-55a90e47476b.png)
