### ISSUE TITLE
GoldHEN not injected

### ISSUE THREAD

**Issue by Knocxx32** [GoldHEN/GoldHEN#157]
Hello,
 I followed the tutorial, I have the PPPWN notification but I do not have the GoldHEN injection. My usb stick is fat32 and even exfat, goldhen.bin at the root of the usb stick. I tested both usb ports, and nothing. a solution ?

**Comment by SiSTR0** [comment]
Try to download again (stage2)[https://github.com/SiSTR0/PPPwn/releases/tag/1.00

**Comment by SiSTR0** [comment]
]
