### ISSUE TITLE
The console was turned off incorrectly after GoldHEN v2.4b17 v9.00 with method PPPwn

### ISSUE THREAD

**Issue by winchesterpro5** [GoldHEN/GoldHEN#167]
After successfully downloading PPPwn and activating GoldHEN v2.4b17 v9.00 , when you turn off/restart/sleep the ps4 console, it turns off as if it were pulled out of the socket. And then it turns on only from the button on the PS4 case, followed by a notification that the console was turned off incorrectly.

**Comment by KrisztianKende** [comment]
To avoid this, turn down the network interface after PPPwn.

```
ip link set eth0 up
./pppwn -a -i eth0 --fw 900 --stage1 stage1.bin --stage2 stage2.bin
ip link set eth0 down
```

**Comment by winchesterpro5** [comment]
@KrisztianKende 
> To avoid this, turn down the network interface after PPPwn.
> 
> ```
> ip link set eth0 up
> ./pppwn -a -i eth0 --fw 900 --stage1 stage1.bin --stage2 stage2.bin
> ip link set eth0 down
> ```

thank you, sleep mode also works fine now =)

**Comment by winchesterpro5** [comment]
> To avoid this, turn down the network interface after PPPwn.
> 
> ```
> ip link set eth0 up
> ./pppwn -a -i eth0 --fw 900 --stage1 stage1.bin --stage2 stage2.bin
> ip link set eth0 down
> ```

Maybe it would be possible to organize this in pppwn or goldhen, so as not to resort to disabling the network interface? What do you think?

**Comment by KIMO-in** [comment]
#187

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18
