### ISSUE TITLE
BinLoader Server on 9090 port

### ISSUE THREAD

**Issue by iTzvbcx** [GoldHEN/GoldHEN#17]
pls auto server permament on or tell how make it in host with bin file any time go to setting click on is drama for my kind

**Comment by Masamune3210** [comment]
Saving option preferences is listed as being added later

**Comment by SiSTR0** [comment]
Hi! autosave server config is done in new version in test, at the moment saves only if you want auto restart servers, in roadmap to config also servers port.

**Comment by SiSTR0** [comment]
Added auto config saving in https://github.com/GoldHEN/GoldHEN/releases/tag/2.1
