### ISSUE TITLE
10.50 support ❤️ 

### ISSUE THREAD

**Issue by ThEWoLf882-42** [GoldHEN/GoldHEN#172]
Hello, I was wondering if it was possible to add 10.50 support to goldhen, my ps4 is stuck on that firmware I can't update it for reason unknown to me

**Comment by CaelThunderwing** [comment]
> Hello, I was wondering if it was possible to add 10.50 support to goldhen, my ps4 is stuck on that firmware I can't update it for reason unknown to me

has been a common updating block since the PS3 Days, but anything like your BD-ROM drive dead/disconnected?

**Comment by alexmuniz10** [comment]
I have a slim with a dead bd drive (bad chip) and I'm stuck on 10.50. Is it possible to have support for 10.50 in the future?

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18
