### ISSUE TITLE
BinLoader seemingly Broken under 11.00

### ISSUE THREAD

**Issue by CaelThunderwing** [GoldHEN/GoldHEN#174]
have noticed that the BinLoader server is just not loading or parsing payloads under 11.00 does make it hard to load into linux via anything really other than pppwn GUI.

(Pi-PPPwn and the Android loader both just end up loading regardless the action taken goldhen instead of the selected payload n custom Stage2. Which could be mitigated just loading the payload from Payload Guest or other means, which cant work with BinLoader apparently non-functional)

**Comment by RandQalan** [comment]
Not sure if same happens with 11.00 as 9.0p
Turn bin loader off wait for connection to error out turn off Ethernet connection turn back on bin loader server then try web versions or payload guest. This works on 9.00 so hopefully it helps you out.

**Comment by Lonewolf81** [comment]
The payload guest does work to load payloads I used it last night after upgrading to 11.00

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18
