### ISSUE TITLE
Rest mode shuts off whole console with error

### ISSUE THREAD

**Issue by korniux** [GoldHEN/GoldHEN#175]
PS4pro 11.00 / GoldHEN v2.4b17.2 / Rest mode setting ON

After going into rest mode PS4 stays in it for a while and after power led shuts off. While powering on it beeps twice, turns on like after full power cycle, and shows error CE-36329-0.

**Comment by NelsonFrancisco** [comment]
Same happens to me.
PS4 Pro as well.
Also happens with full power cycle, not only rest mode.

**Comment by korniux** [comment]
After [GoldHEN v2.4b17.3](https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b17.3) release sleep mode doesn't work at all. Even though I need to long press power button on console.

**Comment by uberclart** [comment]
Same here - PS4 Pro CUH-7116b. Have tried disconnecting from internet via settings, disconnecting via pulling lan cable, disabling FTP and BinLoader, disabling HDCP, disabling power to USB in rest mode, disabling plugins/cheats/patching, removing all USB devices etc. Tried replacing old HDD with 1TB SSD. Any power activity (rest, restart, shut down) results in bad shutdown/HDD scanning and loss of JB etc. :) Thanks for the release though still using it!

**Comment by NelsonFrancisco** [comment]
> Same here -
> 
> PS4 Pro CUH-7116b FW11.00/GoldHEN v2.4b17.3 Have tried disconnecting from internet via settings, disconnecting via pulling lan cable, disabling FTP and BinLoader, disabling HDCP, disabling power to USB in rest mode, disabling plugins/cheats/patching, removing all USB devices etc. Tried replacing old HDD with 1TB SSD. Any power activity (rest, restart, shut down) results in bad shutdown/HDD scanning and loss of JB etc. often showing the "you did not shut down your console correctly" warning, as if in rest mode and then unplugged.
> 
> Thanks for the release though still using it!
> 
> Are there any logs that I can post?

Exact same thing happens to me.

And me too, let me know if there is anything I can do to help.

**Comment by yifanfu** [comment]
Same happened to my PS4 Pro and PS4 Slim

**Comment by KIMO-in** [comment]
Is there any chance to fix this issue in the future ?

**Comment by privacy313** [comment]
Having the same issue here on 2.4b17.3

**Comment by troy0h** [comment]
Same here on 2.4b17.3

**Comment by KIMO-in** [comment]
#187

**Comment by Suikoden4Fans** [comment]
same problem...... :(

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18
