### ISSUE TITLE
 GoldHEN v2.4b17 remote play it doesn't seem to work

### ISSUE THREAD

**Issue by ludetro** [GoldHEN/GoldHEN#177]
try chiaki on pc or ns 
PS4 error: CE-35407-9

**Comment by devKoy** [comment]
@ludetro  Same here. Have you found any solution?

**Comment by devKoy** [comment]
> @ludetro Same here. Have you found any solution?

I think I've found a solution. Might try this one later. https://youtu.be/lnwlOwAQlQE?si=8JJxwISvU2QDwMV0
