### ISSUE TITLE
Remote play issue with Vita on GoldHEN v2.4b17.3

### ISSUE THREAD

**Issue by tdphuochuy** [GoldHEN/GoldHEN#181]
I could remote play to PC's PS Remote Play and Chiaki (both Android and PC) but wasn't able to do it with Vita's PS4 Link (either via direct connection or wifi). PS4 is activated with Apollo.

Errors:
On Vita: "the number for another user was entered" (when signed in to PlayStation Network) or C2-15928-5 (signed out or no account at all, activated with PS4 Relink)

On PS4: CE-35406-8 (activated with Apollo) or CE-35407-9

**Comment by HarryCover78** [comment]
Hello, i have a same issue.  Do you find a solution?
Tanks un advance

**Comment by HarryCover78** [comment]
Hi, little up
Have you a goods news ?

**Comment by tdphuochuy** [comment]
> Hi, little up Have you a goods news ?

I sold the 11.00 and got a 9.00 and it worked perfectly, that was my solution

**Comment by HarryCover78** [comment]
thanks for your feedback.
it's already a good start, have fun :)

**Comment by dhoname** [comment]
also activate via apollo, also CE-35406-8. Connecting from pc or switch via chiaki

**Comment by SiSTR0** [comment]
Check [this](https://github.com/GoldHEN/GoldHEN/issues/177#issuecomment-2172073894)
