### ISSUE TITLE
Gold HEN v17.3 Config save Bug FTP & Bin Loader

### ISSUE THREAD

**Issue by cloud-strife7777** [GoldHEN/GoldHEN#182]
FTP & Bin Loader have save config file bug. Please fix it.

If you activate FTP & bin loader and then deactivate them again, the FTP server is still saved in the config as active 1.

**Comment by SiSTR0** [comment]
Yep this bug is fixed and ready for next release, tnx for reporting

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18
