### ISSUE TITLE
kernel panic when I switch between users ?

### ISSUE THREAD

**Issue by Bsswal** [GoldHEN/GoldHEN#192]
When I switch to another user the device completely shuts down , it happens every time. anyone faced this  problem? 

fw 11.00

goldhen 2.4b17.2

**Comment by SuperArdner** [comment]
yes this also happens on my playstation too, I got the problem it when using goldhen 2.4b.17.2 or 2.4b.17.3

**Comment by KIMO-in** [comment]
I have the same issue

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18
