### ISSUE TITLE
CE-30391-6 Error CMOS Fix

### ISSUE THREAD

**Issue by popad028** [GoldHEN/GoldHEN#2]
I managed to change the date, and the time was kept correctly after several restarts, but after I turned off the power, the date broke. I'm pretty sure the battery is good, it reset because I removed it when I cleaned the ps4. I will repeat the process after I buy a new battery. Thank you for all your hard work.

**Comment by SiSTR0** [comment]
The patch inserted is used to solve the CE-30391-6 problem which is due to cmos errors but does not in any way affect the clock of your console. Yes, your battery most likely needs to be changed
