### ISSUE TITLE
DualShock 4 Controller issues on 11.00

### ISSUE THREAD

**Issue by ccfman2004** [GoldHEN/GoldHEN#203]
The controller works just fine when not in GoldHEN mode but once PPPwn loads GoldHEN 17.3b my Sony DS4 controller starts having button pressing issues where the face buttons don't always work and one tap of a D-Pad sometimes moves the cursor to the end or beginning of a list or will act like I'm holding it and scroll multiple times. 

I am using the CUH-ZCT2U model so I don't know if that is the issue or not.

I don't know what other info is needed to track this issue down. Also this issue happens in all apps I've tried.

**Comment by SiSTR0** [comment]
Sorry but GoldHEN never interact with controller, try another one

**Comment by ccfman2004** [comment]
The controller works perfectly fine until GoldHEN is loaded so something is going on with GoldHEN.

**Comment by ccfman2004** [comment]
Following up I am even more confused as to what is causing the issue than I was before.

The issue seems to start when I have my PS4 formatted 5TB USB drive and an ExFAT formatted USB SSD plugged in at the same time. Don't know why this combination is causing all these controller lag issues. If I only have the PS5 formatted HDD plugged in there is no issue until that ExFAT SSD in plugged in. Even more confusing the issue remains until I disconnect BOTH USB devices. Then the controller issue stop.

If I have one or the other plugged in there I don't notice the lag.

Do you have any idea on what is going on because I certainly don't

**Comment by ccfman2004** [comment]
I think I may have finally found the issue. Not sure why but it seems the OWC USB to SATA adapter I was using for the 1TB ExFAT SSD was somehow causing the issue. When I tried a different adapter I no longer have the controller issues.
