### ISSUE TITLE
Goldhen 2.4b17.3 ps4 pro issues

### ISSUE THREAD

**Issue by NightKnight117** [GoldHEN/GoldHEN#207]
Goldhen not letting me put into rest mode. Every time ps4 put into rest mode with goldhen; it turns off instead.

**Comment by KIMO-in** [comment]
Your ps4 always turn off properly? Or sometimes crashes and giving a bad shutdow

**Comment by NightKnight117** [comment]
It turns off property and it only does in goldhen.

**Comment by jason-eu** [comment]
> Goldhen not letting me put into rest mode. Every time ps4 put into rest mode with goldhen; it turns off instead.

Check issue #209

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18
