### ISSUE TITLE
/system is write-protected in FTP server

### ISSUE THREAD

**Issue by john-tornblom** [GoldHEN/GoldHEN#21]
It seems the FTP server is unable to write to items in the /system folder, e.g., daemon binaries located in /system/vsh/app/...

**Comment by SiSTR0** [comment]
System is not mounted in rw by default, need to send custom ftp command MTRW, let me know

**Comment by john-tornblom** [comment]
Great, that works fine, thanks!

**Comment by SiSTR0** [comment]
nice, you are welcome
