### ISSUE TITLE
Request: Custom slim builds to resolve hang on suspend/shutdown?

### ISSUE THREAD

**Issue by slaway** [GoldHEN/GoldHEN#212]
Hi, I know there's already many issues logged about this, but I'm also affected by the hang on suspend on 2.4b17.3 with fw 9.60. Some people claim, like in #205, that fiddling with the INI to disable the FTP server might help, but even though I've changed it and marked the file as read-only, then shut FTP off on my PS4 and disabled "Connect to Internet", it still doesn't help. The suspend hangs, forcing a hard shutdown and the inevitable possible disk issues that brings.

Since this project isn't open source it can't be rebuilt or modified so I can't test if it would make any difference, but if it's confirmed or at least pretty likely that these issues are indeed caused by the FTP server, could you consider putting up a separate release that includes as little as possible while still allowing users to launch already installed games?

Of course the best thing for everyone would be for this issue to be fixed, but obviously hunting bugs takes effort and time, and if this is quite likely to be the issue perhaps a separate release would at least be a band aid in the meantime for users affected.

While I'm pretty tech savvy I'm still pretty new to the PS4 softmodding stuff so apologies if I've overlooked something.

Anyway, thanks for your work.

**Comment by ps4rokx** [comment]
Using any version of luckfox PPPWn and activate goldhen... Now just found 1 games which never occurred to restart or shutdown problem... I found on Trine 5, which is never going to shutdown or restart problem.. playing multiple games randomly and when u need to shutdown or restart, just open Trine 5 games and close the game... Just it never happened on shutdown or restart problem, today I tested 10 times a row.. this tricks just magic to works. And I success...

**Comment by Chbich62** [comment]
Même problème sur PS4 pro, je ne sais plus quoi faire à part attendre une mise à jour.

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18
