### ISSUE TITLE
[Suggestion] A way to ignore folders and subfolders for PKG installer

### ISSUE THREAD

**Issue by CHOUAiB** [GoldHEN/GoldHEN#215]
i have an external HDD with a lot of folders and files. when GoldHen searching for packages in subfolders it takes a long time, is there anyway to ignore scanning folders and subfolder like "ventoy" uses a file called ".ignoreventoy" when it presented in a folder "ventoy" ignore scanning this folder, my suggest is a solution for ignoring unnecessary folders like "ventoy" did.

**Comment by IvoNexus** [comment]
I’ve seen something similar in PS2, where you can limit how many dives can do in subfolders like 10 max, but can’t go beyond the 10th subfolder. I doubt anyone will put all folder names/paths, which will want to skip in a manifest, a custom install path will be better I think.
