### ISSUE TITLE
ftp server is failed to setup IP (GoldHEN_v2.4b17.3)

### ISSUE THREAD

**Issue by alimp5** [GoldHEN/GoldHEN#216]
greetings

at first, thank you a lot ❤️ 

the previews version of `GoldHEN_v2.4b17` was OK without any problem to enable/disable and launch FTP Server.
but it had problem to enable Read & Write access to modify the contents of HDD files.

today i downloaded the latest version `GoldHEN_v2.4b17.3`. the read & write issue on HDD fixed and it's OK. but FTP server is failed to issue and assign an IP address to device.

**Comment by IvoNexus** [comment]
FTP server never had the role to assign IP address, but to open port and start the service, what exacly you getting as error or feedback from the server, does the console has active connection with assigned IP and enabled "Internet access"?

**Comment by SiSTR0** [comment]
Try new version https://github.com/GoldHEN/GoldHEN/releases/tag/2.4b18
