### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by samfadel** [GoldHEN/GoldHEN#223]
In goldhen 2.4b 18 cheat menu "cheat selection" Remove "all cheats" seems not necessary ,keep "installed games" to save more storage

**Comment by SiSTR0** [comment]
Honestly I would prefer to keep the ability to download all the cheats, both because the full size of the cheats is ridiculous, so no big waste of space, and because you are not tied to continuously updating when you use new games, not everyone keeps the PS4 always connected to the internet.
