### ISSUE TITLE
Rest mode issue

### ISSUE THREAD

**Issue by Assassin77710** [GoldHEN/GoldHEN#25]
I am using the latest gold hen v 2.1.1 it shows it has some rest mode improvements but still when it is left for a hour or a 2 and then I turn it on it sometimes crashes or it turns on but with no gold hen

**Comment by Assassin77710** [comment]
Ya I also got shocked about 2.1.1 I got it from the kameleon host I trust it the most (no promotions) then i went to gold hen then about gold hen and then it showed the 2.1.1 I didn't use any other payload just gold hen only loaded

**Comment by SiSTR0** [comment]
ok this version will release today, if you get another iusse please report it in GoldHEN test server on discord.

**Comment by Assassin77710** [comment]
Great
