### ISSUE TITLE
PS4 fat can't enter rest mode

### ISSUE THREAD

**Issue by therealsamsquanch** [GoldHEN/GoldHEN#27]
GoldHEN works as intended, but when I'm done playing and try to put the console on rest mode, its white light keeps pulsing forever, it never goes orange, indicating that the console is sleeping.  Without it, my PS4 can go in and out of rest mode, no problem there. Model is CUH-1001A, and I've tried GoldHEN 2.0, 2.0b and 2.1.1. I've tried Kameleon and several other hosts, always the same result.

I don't have other payloads installed, and I even restored my PS4 to factory settings just to be sure.

Let me know if there's a way to provide logs.

**Comment by SiSTR0** [comment]
very strange, try to get klog while PS4 is going in rest mode. contact me on GoldHEN test server discord
