### ISSUE TITLE
[Feature Request] Disable auto config update

### ISSUE THREAD

**Issue by nickcat325** [GoldHEN/GoldHEN#29]
There is a setting in the config to auto start FTP and the BinLoader. It would be nice to have an option like ConfigAutoUpdate that you could set to 0. This would make checking the boxes in the GoldHEN settings not update the config.

Hopefully I am explaining this correctly.

**Comment by kmeps4** [comment]
This is gonna be taken as a request not a bug.. please contact me or Sistro in open orbis discord server.
