### ISSUE TITLE
PS4 Pro Goldhen 2.1.2 Sleep mode not working

### ISSUE THREAD

**Issue by jorgemuela** [GoldHEN/GoldHEN#31]
PS4 Pro Goldhen 2.1.2 Sleep mode not working, 

Hi, 
I tried from 2 different sites nightking and gamerhack which were working perfect on previous Goldhen versions.

PS4 Pro
Fw 7.55
Ethernet auto settings
Wifi auto settings
Enchanced mode activated

Let me know if you need any more data Im happy to assist!

**Comment by kmeps4** [comment]
Hello I can assist you... please write do my discord: Kameleon_#2596

**Comment by jorgemuela** [comment]
> Hello I can assist you... please write do my discord: Kameleon_#2596

Thank you, sent invitation from my discord ultimatezero00#1743
