### ISSUE TITLE
2.1.2 5.05 bug ?

### ISSUE THREAD

**Issue by spotanjo3** [GoldHEN/GoldHEN#33]
I played Metro Exodus with goldenhen 2.1.2 for 5.05 and it seems to crashed several time and corrupt my save. And shut down my PS4. 

Good thing that I backed up save for Metro Exodus so I came back to 2.1.1 and never had a problem. It could be a bug.

**Comment by SiSTR0** [comment]
tnx for reporting but 2.1.2 update touches only GoldHEN setting config parser that is no related with games or hb

**Comment by spotanjo3** [comment]
Hey! 👍 

Okay but can you explain why it does happened to 2.1.2 ? It didnt happened to 2.1.1. I am playing it for few days with 2.1.1 and no issues but had an issues with 2.1.2 for the fhird time ?

**Comment by SiSTR0** [comment]
dunno, as I say 2.1.2 touch only ShellUI stuff not related to game execution, try to get klog that should help to understand better what happenend

**Comment by spotanjo3** [comment]
I dont know about klog. Never heard of klog.
