### ISSUE TITLE
[Request] Show tittle ID

### ISSUE THREAD

**Issue by PS3-4K-Pro** [GoldHEN/GoldHEN#36]
Could an option to show the tittle ID be added, just like OrbisToolbox?

Also the dex option to delete the save data only, dlc or update.

**Comment by SiSTR0** [comment]
ok will take this feature request for next releases

**Comment by dirkabel** [comment]
I would like this feature also. ;-)

**Comment by RandQalan** [comment]
Thi should be closed. 2.3b2 can do this.
