### ISSUE TITLE
Problem close game use PS button and select close game

### ISSUE THREAD

**Issue by Fall0n** [GoldHEN/GoldHEN#37]
regret my poor English spelling.  I have dyslexia.  But I do my best ..

The problem started when 2.2 goldhen. My ps4 pro fw9 takes an extremely long time to close of games it takes about 15-20 minutes while goldhen 2.1.2 does it in a few seconds. Anyone else with this problem?

**Comment by Kimantonsson** [comment]
I have same problem

**Comment by dirkabel** [comment]
Not here

**Comment by RandQalan** [comment]
Usually  this is a Db problem. 
1 move all to ext0 official or
2 use this may fix problem make sure if IHDD backup Db.
https://pkg-zone.com/details/SAAT29385

**Comment by kmeps4** [comment]
Try out latest GoldHEN 2.2.4
