### ISSUE TITLE
Version Read out of Games in Cheatmenu.

### ISSUE THREAD

**Issue by ApophysX** [GoldHEN/GoldHEN#38]
The version of the games are not displayed correctly in the Golden Cheatmenu (Share Button).

Example:
Assassin's Creed Valhalla V5.10 is installed (Long Press Share) shows V1.00.
Kena V1.16 is installed (Long Press Share) shows V1.00.

But the problem is not available for all games.

PS4 Pro FW.9.00

**Comment by SiSTR0** [comment]
Cheat menu reads the version correctly, you can check it from the pkg information menu (where you also see the size of the game and update history). I'm afraid the problem is that you are using some repack that is not done right.
