### ISSUE TITLE
[Request] Smal wish for new versions: Goldhen indicator at homescreen

### ISSUE THREAD

**Issue by dirkabel** [GoldHEN/GoldHEN#39]
Hi,

It would be fine, if goldhen put a smal indicator at the ps homescreen to see, it's already loaded well.
Sonething like a smal icon or so.
Orbis Toolbox for example puts a large white text with red background in the upper right corner. This is to much, but a small "GH" or something else would be fine.

Dirk

**Comment by kmeps4** [comment]
Sistro is already aware and not an issue. Gonna close
