### ISSUE TITLE
Goldhen crashes ShellUi 

### ISSUE THREAD

**Issue by ac2pic** [GoldHEN/GoldHEN#4]
Running Goldhen then running Mira causes it to black screen.
Mira works fine if it is ran first.

**Comment by SiSTR0** [comment]
I think it is not a GoldHEN iussue but will check, need you fw and Mira version you used

**Comment by ac2pic** [comment]
v9.00 and the version from `payloads (3.50.9.00).zip`

**Comment by SiSTR0** [comment]
I would wait for a stable version of Mira before doing the various compatibility tests

**Comment by CyB1K** [comment]
You need to run mira first, then run goldhen. Mira does a softreset on the console if it already has hen it will stay on the blackscreen of doom until you restart the console.

**Comment by SiSTR0** [comment]
I close this issue until a stable version of Mira will be released
