### ISSUE TITLE
"Close Application" button missing

### ISSUE THREAD

**Issue by TheRozitaKnight** [GoldHEN/GoldHEN#40]
~~The "Close Application" button doesn't appear on the options menu on v2.2.1.~~

Never mind, it was an issue with the host I was using. The issue can be closed.

**Comment by remlei** [comment]
I have the same issue...

This issue only exist in 2.2.1 mainly in homebrew applications such as PS4 Temperature,  Apollo Save Tool, Payload Guest, etc.....

But the "Close Application" still showing up on retail games (fpkg or not).

**Comment by TheRozitaKnight** [comment]
Did you try sending the payload with netcat? That fixed the issue for me.

**Comment by remlei** [comment]
> Did you try sending the payload with netcat? That fixed the issue for me.

tried it multiple times with netcat and nope, its still the same. only homebrew apps doesnt have the "closed application" option.

**Comment by SiSTR0** [comment]
Fixed in v2.2.2, tnx for reporting it
