### ISSUE TITLE
Hide Cheat Menu button

### ISSUE THREAD

**Issue by TheRozitaKnight** [GoldHEN/GoldHEN#41]
I'm used to the close button being the first in the options menu. Could a toggle be added to hide the GoldHEN Cheat Menu button? Or an option to disable the cheat menu completely?

**Comment by remlei** [comment]
same here, I prefer if this option is at way bottom of the selection.

I already have the muscle memory on closing games on this fashion and always entering the goldhen cheats menu.

**Comment by SiSTR0** [comment]
Customizable on new version [v2.2.3](https://github.com/GoldHEN/GoldHEN/releases/tag/2.2.3)
