### ISSUE TITLE
How to update GoldHEN from 2.0b to the latest version 2.2.1 in a Jailbreak PS4

### ISSUE THREAD

**Issue by plike85** [GoldHEN/GoldHEN#43]
I used 2.0b to jailbreak last month.
The cheat function is fantastic, and want to try.
How can I update GoldHEN from 2.0b to the latest version 2.2.1 in a Jailbreak PS4?

**Comment by Masamune3210** [comment]
Depends on how you are doing things, since the question is relatively simple I'm going to assume you are using a webhost in which case you will have to wait until whoever you are using integrates the new update, or switch to one that has in the meantime until they do

**Comment by SiSTR0** [comment]
Use bin and some payload sender client or netcat

**Comment by plike85** [comment]
> Use bin and some payload sender client or netcat

NetCat says it already has a payload installed in PS4 and cannot update

**Comment by Masamune3210** [comment]
You have to shut the ps4 down and turn it back on to clear out the old version first before you can push the new version

**Comment by plike85** [comment]
> You have to shut the ps4 down and turn it back on to clear out the old version first before you can push the new version

Understood.
I used a new website(https://psgo.gitee.io/900/) to load goldhen 2.2.2
