### ISSUE TITLE
PS4 9.50

### ISSUE THREAD

**Issue by keyhod** [GoldHEN/GoldHEN#47]
Is there ever gonna be GoldHEN for 9.40?
If not, is there any alternatives?
I tried jailbreaking my PS4 with 9.40 but it said ,,Page is not reacting. Do you want to close it?''
If I click ,,Cancel'' this message shows up again, but if I click ,,OK'' It says ,,There's not enough memory'' and done.
I tried redoing this and - nothing.

Does anyone know how to fix this issue?

**Comment by lburbanoulloa** [comment]
Man, the vulnerability in the PS4 firmware that allows to make jailbreaking was fixed in firmwares over 9.00. I'm pretty sorry but at the moment is impossible. You must to wait and to don't upgrade the firmware while do it
