### ISSUE TITLE
[Request] Resolution Menu

### ISSUE THREAD

**Issue by PS3-4K-Pro** [GoldHEN/GoldHEN#48]
Just as Cheats menu, would be nice if we get a resolution menu for those games that have resolution patches.

**Comment by kmeps4** [comment]
You mean like 60FPS patches from Illusion???

**Comment by Wojtaz0w** [comment]
That would be great! Maybe also built-in 60fps patches if it's possible...

**Comment by illusion0001** [comment]
We have some prototype working, patches will have to be made manually like cheats but it will no longer require a computer to run it. Also means it work with disc games too.

**Comment by RandQalan** [comment]
Most likely soon

**Comment by kmeps4** [comment]
Gonna close. This is not a GoldHEN issue
