### ISSUE TITLE
Mortal kombat xl 

### ISSUE THREAD

**Issue by bladehb** [GoldHEN/GoldHEN#49]
I have the problem with GoldenHen 2.2.2 that it stutters badly as far as I want to use it with mortal kombat XL, but I take GoldenHen 2.1.2 everything is super but I don't have any advantages like fast cheating etc

**Comment by DanAQ-ptbr** [comment]
Mortal kombat xl, Same with GoldenHen 2.2

**Comment by bladehb** [comment]
How do you mean that??  It needs to be fixed that's for sure because GoldenHen 2.2.2 only causes trouble for Mortal kombat XL vers 1.0 I hardly take GoldenHen 2.1.2 it's gone but I don't have a cheat manager for that

**Comment by DanAQ-ptbr** [comment]
No "Cheats" for US to Mortal Kombat XL [CUSA03679] v01.00, unless ignore the "stutters badly" (EX.: During the X-Ray).

Mortal Kombat XL [CUSA03679] v01.00 "stutters badly" in GoldHen 2.2, GoldHen 2.2.1 and GoldHen 2.2.2, unless updating the game to 01.04, 01.05 or 01.06, losing the "Cheats".

I (no time) do not find a host with GoldHen 2.1.2.

We, have to wait future GoldHen.

I use GoldHen v2.2 because "**Offline PS2 Cheats Works on Goldhen 2.2 but not on 2.2.2**"

**Comment by bladehb** [comment]
The game stutters very badly during cutscenes and intro, and only with verse 1.0 but I assume 2.1.2 is all good but not with 2.2.2 because it is unplayable but yes I can only hope that it will be better with the next goldHen  is running and being fixed, will you take care of it?  Or does someone else do it? I just think it's important to give feedback so you know what works and what doesn't

**Comment by bladehb** [comment]
Also, why ps2 cheats?  Since when can you cheat on GoldenHen ps2 games?  That would be new to me.

**Comment by DanAQ-ptbr** [comment]
<pre>Offline PS2 Cheats style "Goldhen Menu" Works only in GoldHen v2.2.

You have to convert the "PS2 RAW CODES" to "PS4 EMULATOR" (jak v2).

More instructions to convert are here: [ <a href="https://github.com/GoldHEN/GoldHEN_Cheat_Repository/issues/27">https://github.com/GoldHEN/GoldHEN_Cheat_Repository/issues/27</a> ]




Example: The "PS2 RAW CODE" format...
---- ----
"GRAND THEFT AUTO SAN ANDREAS (SLUS_209.46 - crc 2C6BE434)"
Jetpack (L1 12x)
2064AEC0 B2904560
Money inf
0070A246 00000097
---- ----




You save a file "SLUS20946_01.00.json", with that content ...
---- ----
{
	"name":"Grand Theft Auto San Andreas",
	"id":"SLUS20946",
	"version":"01.00",
	"process":"eboot.bin",
	"mods":
	[
		{
			"name":"Jetpack (L1 12x)",
			"type":"checkbox",
			"memory":
			[
				{
					"offset":"808024AEC0",
					"on":"604590B2",
					"off":"00000000"
				}
			]
		},
		{
			"name":"Money inf",
			"type":"checkbox",
			"memory":
			[
				{
					"offset":"808030A246",
					"on":"97",
					"off":"96"
				}
			]
		},
	],
	"credits":
	[
		"DanAQ-ptbr: 20220415"
	]
}
---- ----




GoldHen v2.2 will show the "Cheats" to turn "ON" or "OFF".

I use FTP, maybe you can use the GoldHEN_Cheat_Manager [ <a href="https://github.com/GoldHEN/GoldHEN_Cheat_Manager">https://github.com/GoldHEN/GoldHEN_Cheat_Manager</a> ]
to install the cheat ("SLUS20946_01.00.json").</pre>

**Comment by bladehb** [comment]
oh yes, where do you actually get shn and Json cheat files??

**Comment by DanAQ-ptbr** [comment]
I recently found out how to convert "PS2 RAW CHEATS" to "EMULATOR (jak v2) PS4".

For now..., we need to create our own "JSON" file from "PS2 RAW CHEATS".

"PS2 RAW CHEATS": <a href="https://gamehacking.org/game/103759">https://gamehacking.org/game/103759</a>

**Comment by kmeps4** [comment]
Thx I will close following Thread as I mention before SLUS/SLES it's not supported to attach GoldHEN cheat menu...
