### ISSUE TITLE
Offline PS2 Cheats Works on Goldhen 2.2 but not on 2.2.2

### ISSUE THREAD

**Issue by DanAQ-ptbr** [GoldHEN/GoldHEN#50]
<pre><b>HOW TO CONVERT "PS2 RAW CHEATS" TO EMULATOR (jack v2) "PS4 GOLDHEN JSON CHEATS"</b>

FIX 2022-04-19

Example:

FLATOUT 1, SLUS_209.01 (E0127F2D)
Cash inf (9,999,999)
<b>208CA4FC 0098967F</b>

THERE ARE 3 (three) STEPS...

<b>1st) PS2 HEX VALUE to PS4 EMULATOR:</b> The values in PS2 are in "BIG ENDIAN"
     while in the emulator (jak v2) the values are in "LOW ENDIAN" (inverted).
     Just invert the bytes (value) being like this...

FLATOUT 1, SLUS_209.01 (E0127F2D)
Cash inf (9,999,999)
208CA4FC <b>7F969800</b>

<b>2nd) PS2 TYPES:</b> The first digit in "PS2 RAW CODE ADDRESS" appoint for the types of value.
     Example: 2 = WORD (4 bytes 0x00000000); 1 = SHORT (2 bytes 0x0000); 0 = BYTE (1 byte 0x00).
     In the "Memory Address", just replace the first digit to 808.
     The "Cheat" above will look like this...

FLATOUT 1, SLUS_209.01 (E0127F2D)
Cash inf
Cash inf (9,999,999)
<b>80808CA4FC</b> 7F969800

<b>3rd) PS4 EMULATOR (jak v2):</b> Subtract 0x400000 from the memory address...

  80808CA4FC
-   0x400000
____________
  <b>80804CA4FC</b> 7F969800

NOTE: WORKS ON GOLDHEN v2.2;
      UNFORTUNATELY NEW GOLDHEN (v2.2.2) DOES NOT LIST THE CHEATS
      (ignores SLES?????*.json and SLUS?????*.json, listing only CUSA?????*.json);
      I STILL DON'T UNDERSTAND HOW THE "ON" AND "OFF" COMMANDS WORK IN JSON,
      SOME GAMES ARE TURNING OFF THE "CHEAT".

---- ----
ATTENTION TO THE TYPES OF BYTES ON PS2, EXAMPLE...

WORD (4 bytes) .. <b>200</b>XXXXX <b>3F800000</b> (float value 1.00)
                  converts to -> <b>80800</b>XXXXX <b>0000803F</b> (float value 1.00)
                  subtract 0x400000 = <b>807FC</b>XXXXX <b>0000803F</b> (float value 1.00)

SHORT (2 bytes) .. <b>100</b>XXXXX ????<b>03E8</b> (int value 1,000)
                   convert to -> <b>80800</b>XXXXX <b>E803</b> (int value 1,000)
                   subtract 0x400000 = <b>807FC</b>XXXXX <b>E803</b> (int value 1,000)

BYTE (1 byte) .. <b>000</b>XXXXX ??????<b>63</b> (int value 99)
                 convert to -> <b>80800</b>XXXXX <b>63</b> (int value 99)
                 subtract 0x400000 = <b>807FC</b>XXXXX <b>63</b> (int value 99)

XX = no change
?? = unused bytes
---- ----

GOLDHEN JSON FINAL CHEATS (SLUS20901_01.00.json)...
................................................................................

<b>{
	"name":"FlatOut 1",
	"id":"SLUS20901",
	"version":"01.00",
	"process":"eboot.bin",
	"mods":
	[
		{
			"name":" Cash inf",
			"type":"checkbox",
			"memory":
			[
				{
					"offset":"80804CA4FC",
					"on":"7F969800",
					"off":"7E969800"
				}
			]
		}
	],
	"credits":
	[
		"DanAQ-ptbr: 20201025, 20201028, 20210316, 20220404"
	]
}</b>

................................................................................

OBS.: save the "SLUS20901_01.00.json" in UTF-8 to show the "PS4 System Symbols" Hand (good)
[ https://www.psxhax.com/threads/official-ps4-symbol-codes-by-bannerr3-bann3r-via-hydrogenngu.2578/page-2 ].</pre>

**Comment by kmeps4** [comment]
Hello... Do you have discord account?

**Comment by DanAQ-ptbr** [comment]
No discord, no facebook, no twitter..., offline style.

**Comment by kmeps4** [comment]
ok GoldHEN 2.2.2 Only Attach to CUSAXXXXX... Maybe in future we will add support for SLUS/SLES cheats... thx for the report.
