### ISSUE TITLE
Some games cannot start (black screen) with goldhen 2.2.2

### ISSUE THREAD

**Issue by FmT0** [GoldHEN/GoldHEN#54]
I cannot start 3 games : CUSA26636 Atelier Sophie DX CUSA26637 Atelier Firis DX and CUSA26638 Atelier Suelle DX with last goldhen 2.2.2 Going back to goldhen 2.1.2 is fine. 
With 2.2.2, it stays at a black screen. Usually it loads a save file right from the start before the disclaimer screen. If I delete the save I can start the game and can save, but cannot start the game if a save exist. Tested with both fpkg and physical version.

**Comment by RandQalan** [comment]
2.2.4 wish out KLog enabled.

**Comment by kmeps4** [comment]
Try out GoldHEN 2.2.4
