### ISSUE TITLE
[Request] In-Game Audio Playback while in Remote Play

### ISSUE THREAD

**Issue by L4T3-D4Z3** [GoldHEN/GoldHEN#55]
Hi there,
first off ty for your work!

Would it be possible to enable music playback whilst playing in remote using e.g. the stock media player [CUSA02012, 4.01]

When I tried, this pop-up message appeared:
 'Cannot listen to music in the background while in Remote Play'

**Comment by RandQalan** [comment]
Thi may never work because of S##y security. This would require 2 app not sandbox access. Problem never happen.

**Comment by kmeps4** [comment]
This is not a GoldHEN issue.. gonna close it
