### ISSUE TITLE
Payload Server freezes with an empty closed connection.

### ISSUE THREAD

**Issue by marcussacana** [GoldHEN/GoldHEN#56]
I tried make my program detect if the Payload server is available by trying connect the server,
After confirmed, If I close the program without send any payload, the Payload Sever keep 'freezed'
while I don't restart the server in the Goldhen options.

If you can't reproduce just say, I think I can do build of my tool in a way that bug will allways happen.

Isn't a goldhen problem, but I noticed as well, sometimes, if a payload crash (In my case with segfault),
the Goldhen don't accept more payloads while I don't restart my console.
This is more a problem of the payload itself then I'm just commenting instead fire an issue.

I'm using Goldhen 2.2.2, PS4 Slim 6.72

**Comment by SiSTR0** [comment]
binloader don't make any check on bin, so if arrive just only 00 can crashes all, atm no way to check payload integrity. try to sniff exactly what you sent

**Comment by marcussacana** [comment]
Yup, but it's strange keep 'waiting' for a closed connection with 0 length instead wait for new connections again...
Well, whatever, if you think isn't worth to fix it.

**Comment by SiSTR0** [comment]
you can check binloader status with a HTTP GET /status, it should return "ready" with status code 200

**Comment by marcussacana** [comment]
Fine, thanks for the hint, I didn't know about this API
