### ISSUE TITLE
Breaking system features

### ISSUE THREAD

**Issue by EnekoT2001** [GoldHEN/GoldHEN#57]
Idk why I have to explain this since it’s so basic, but long pressing share is literally used by the ps4 os to perform certain functions, in my case and settings it’s used to open the share menu and choose to save the replay, I have the 1 click screenshot and long press menu setting.

Now I can’t open the menu, and I can’t disable the cheat menu I don’t even care about, and I don’t want to just change the settings so one click is opening the menu because it takes TIME to load and I want to play not to wait for a menu to load so I can save a screenshot, I want to click and screenshot saved, now idk what to do, great work -.-

Couldn’t u add an option menu in settings to choose whether to disable/enable the cheat manager or to choose which key combination should be pressed to open it? Seems very basic to me idk

**Comment by kmeps4** [comment]
This is not really an issue
