### ISSUE TITLE
Loading automatically numbered cheats

### ISSUE THREAD

**Issue by Contra49628** [GoldHEN/GoldHEN#58]
Cheat files created by others with the same version number are not loaded due to automatic numbering. I suggest some formats to fix this:

Cheat file format

CUSAXXXXX_XX.XX.json
CUSAXXXXX_XX.XX_X.json

Custom Cheat file format

CUSAXXXXX_XX.XX_ccf.json
CUSAXXXXX_XX.XX_ccf_X.json

Of course, it should be possible to load these cheats on one screen, separated from each other, and a warning text should be placed on the screen:

"Preferably only use one cheat set at a time to avoid errors and crashes!"

**Comment by kmeps4** [comment]
Thats on the ToDO List: "Multi Cheat support"
