### ISSUE TITLE
FPS drop on Final Fantasy VII with Goldhen 2.2.2

### ISSUE THREAD

**Issue by BlackHaste** [GoldHEN/GoldHEN#65]
When the submarine section starts there is a massive drop of fps going down to 1 fps, this happens on 2.2.2 but not on 2.1.2.

**Comment by SiSTR0** [comment]
Hi! sorry for late reply, maybe this problem is due to tty redirect that lag, I will send you a version without for test, contact me on discord if you can.
Anyway thank you for report

**Comment by TheRazerMD** [comment]
Hey @SiSTR0, was this lag/fps drop fixed in the 2.3 betas or is it still there? Also did you get any more reports on other games?

**Comment by BlackHaste** [comment]
Sorry to say i don't have the save anyomre to test it.

Take note that am talking about the PS4 version of the classic Final Fantasy VII, not the remake.

**Comment by SiSTR0** [comment]
Disable klog tty redirect in new version [v2.2.3](https://github.com/GoldHEN/GoldHEN/releases/tag/2.2.3)
