### ISSUE TITLE
Doesn't play games why?

### ISSUE THREAD

**Issue by dodi7x** [GoldHEN/GoldHEN#66]
Hello, how are you, when I want to play games, it says that the memory of the device is full, but it has 17 GB of unused space, what is the solution, thank you

**Comment by SiSTR0** [comment]
Dunno it is not related to GoldHEN try to get a largest HDD

**Comment by Amirhakin** [comment]
> Dunno it is not related to GoldHEN try to get a largest HDD

When will the first copy of the PS4 console be released? 9.0.5
