### ISSUE TITLE
NEED SISTRO TO DELETE 2 CHEAT IN 1 GAME VERSION, THAT'S MAKE GAME CRASH!

### ISSUE THREAD

**Issue by Ardhazz** [GoldHEN/GoldHEN#68]
Need Sistro to update his GoldHen and delete two cheat at one version game. Just choose one, because if two the game Will be crash, like Bloodborne when activate it!

**Comment by Masamune3210** [comment]
....just don't activate both chests at once then? I'm assuming if it made it into the repo, it's likely for a reason

**Comment by Masamune3210** [comment]
Also, correct me if I'm wrong, but aren't the cheats an entirely different repo?

**Comment by Scalerize** [comment]
> Also, correct me if I'm wrong, but aren't the cheats an entirely different repo?

Correct, they belong to ps4trainer

**Comment by SiSTR0** [comment]
Actually GoldHEN supports only one cheat at time for this reason and when will support multiple cheat files, will always enable cheat of another cheat file if no other are set
