### ISSUE TITLE
Trophy timestamps not updating on 9.00 

### ISSUE THREAD

**Issue by 44daniel** [GoldHEN/GoldHEN#70]
Good to all developers, my problem is:
recently update from 5.05 to 9.00, but shows blank trophy timestamps with GoldHen 2.1.2 and 2.2.2 
how can I solve that?
please,
 my  model ps4 is CUH-7115B (ps4 pro)

**Comment by 44daniel** [comment]
test (blank trophy timestamp)
--goldhen 2.0b2 ---- solved
--goldhen 2.1.2 ----- not solved
--goldhen 2.2.2------ not solved
the problem is goldhen 2.x.x, please solved

**Comment by SiSTR0** [comment]
Hi @44daniel, can you contact me on discord? https://discord.gg/pkUgjDGN
