### ISSUE TITLE
Can't load game save Using 2.2.3

### ISSUE THREAD

**Issue by Scalerize** [GoldHEN/GoldHEN#72]
I Was trying to load my save in Final fantasy Xii CUSA05532 V1.07 while goldhen 2.2.3 was loaded, When i press load game The game's music keeps playing but no load menu shows up, only black screen instead of a prompt to choose which save to load  I Kept waiting 5 whole minutes and no prompt appeared. So i turned off my ps4 and loaded 2.2.2 and The Game instantly showed my save files without any issues.

**Comment by RandQalan** [comment]
Turn on KLog settings enable TTY redirect will fix this had same problem with 1.08

**Comment by 44daniel** [comment]
desactive cheat menu

**Comment by RandQalan** [comment]
> KLog settings----- this option is enabled in goldhen 2.2.2, but it gives problems in ff7 remake I think that the feature: Klog Server has a problem

I known it's causing problems. Try 2.0b2 compare 2.0b2 runs games correctly  every since added in 2.1 and above slowdown not running fmvs stuttering.

**Comment by RandQalan** [comment]
2.2.4 with  KLog off now works. No lag AFAIK test incomplete.

**Comment by SiSTR0** [comment]
Thanks for reporting, should be fixed in new [v2.2.4](https://github.com/GoldHEN/GoldHEN/releases/tag/2.2.4)
