### ISSUE TITLE
Apollo Save Tool PROBLEM (w/ 2.2.3)

### ISSUE THREAD

**Issue by Amethxst** [GoldHEN/GoldHEN#73]
Me and many others friends have problems with "Apollo Save Tool" started via GoldHEN 2.2.3 (which does NOT happen if you try to boot using version 2.2.2).

Problems encountered:
- No app notifications appear
- With the latest versions black screen starts
- With previous versions the images/layouts are not loaded correctly
- Freeze the app on many options

I reported the problem to the founder and he told me to write the problem here (given his absence in the next few days)
In case it can be solved by SiSTRo excellent, otherwise it does nothing and we will have to wait for the creator
(it seemed correct to me to report everything since bucanero is present in the cc)

Extra: Tested on 5.05 and 9.00

**Comment by Scalerize** [comment]
I'm having problems with 2.2.3 too. Highly unstable

**Comment by Carter1190** [comment]
probs cuz apollo hasnt been updated,dont expect things to work with new releases right away

**Comment by RandQalan** [comment]
> I'm having problems with 2.2.3 too. Highly unstable and problematic

I Agree and almost 100% positive it is KLog server doing it. It should. have options to totally disable it.

**Comment by RandQalan** [comment]
Try 2.2.4 might fix problems.

**Comment by SiSTR0** [comment]
Thanks for reporting, should be fixed in new [v2.2.4](https://github.com/GoldHEN/GoldHEN/releases/tag/2.2.4)
