### ISSUE TITLE
Pregunta cusa y version

### ISSUE THREAD

**Issue by bombardeo38** [GoldHEN/GoldHEN#74]
Quitaste la función de mostrar cusa y versión o piensas volver a añadir después para mi era muy útil gracias

**Comment by Scalerize** [comment]
I Think they removed it cause it was causing lag, Not quite sure though

**Comment by kmeps4** [comment]
Please next time report on English.. labels are still wip.. gonna be added when those are out of beta... gonna close thread since this is not a real issue
