### ISSUE TITLE
[Request] Please Toggle GoldHen logo/PS plus logo

### ISSUE THREAD

**Issue by bishalqx980** [GoldHEN/GoldHEN#76]
Can you please add a toggle button inside GoldHen settings so that we can switch/toggle PS logo/GoldHen logo on the home screen left corner...
but keep the quick redirect to GoldHen menu on click the logo //
Love you SiSTRo & also your hard work ... Thanks...❤️
Sorry, my English is not so good...Do you understand what is said 🙃

**Comment by Scalerize** [comment]
How does the goldhen icon replacing ps plus button bother you in any way  ?

**Comment by Masamune3210** [comment]
Some people just like keeping everything looking stock, its a preference usually not a bother lol

**Comment by kmeps4** [comment]
This is not a issue. I'm gonna close this one. Please go to GoldHEN discord if you have any request

**Comment by bishalqx980** [comment]
> This is not a issue. I'm gonna close this one. Please go to GoldHEN discord if you have any request

Link please SIR...

**Comment by kmeps4** [comment]
Here's the GoldHEN discord link: https://discord.gg/bTae8ejy
Please go to "Request" Channel and Sistro could take it into consideration for next releases.. thx a lot.
@RandQalan if you go over GoldHEN discord to spam I'll direct ban you!!!

**Comment by RandQalan** [comment]
> 

Don't worry I just I am not carrying anymore. Your threats and rude attitude made me not care anymore!
