### ISSUE TITLE
Soft Panic Attack after goldhen is loaded maybe due to extermal hdd attached

### ISSUE THREAD

**Issue by shubham-sakharkar** [GoldHEN/GoldHEN#78]
Hello @SiSTR0 I have slim model with 1 TB External HDD attached, also using ESP32-S2 Mini with Stooged Auto USB, sometimes when Loading ExFat is done, and Loading GoldHEN starts it produces a panic attack or sometimes after goldhen is loaded within 1 or 2 seconds it generates panic attack, have you ever seen a issue like this? is it due to HDD or its problem with esp or goldhen, please share some thoughts.

**Comment by SiSTR0** [comment]
Don't think it is related to GoldHEN, try to load GoldHEN via binloader or change method. I don't use esp32 sorry, try to ask to @kmeps4 on twitter or discord

**Comment by shubham-sakharkar** [comment]
Okay
