### ISSUE TITLE
Problema con juego 

### ISSUE THREAD

**Issue by bombardeo38** [GoldHEN/GoldHEN#79]
Buenas y gracias por todo lo primero lo segundo hacia tiempo que la niña no jugaba al minecraft desde la 2.2.2 y resulta que claro apartar de la 2.2b.3 se implemento el reconocimiento verdadero de versión pues el juego en la versión 1.0.0 me lo reconoce como la 1.0.2 y la niña se dio cuenta de que así los trucos no le funcionan pero si en vez de el 2.2.4 utiliza el 2.2.2 si y el goldhen cheats manager si lo reconoce como 1.0.0

**Comment by kmeps4** [comment]
Please next time report on English.. GoldHEN 2.2.4 does correct game version detection.. usually remaster pkg (bass + update) will install as 01.00.. but latest GoldHEN will recognize the correct version.. send me the CUSA and I can upload the version needed. Gonna close since this is not a issue
