### ISSUE TITLE
Eror cheats 

### ISSUE THREAD

**Issue by Hasssan13** [GoldHEN/GoldHEN#80]
Hello, the cheats of dragon quest XI are not good cause v 1.01 doesn't exist and also the v 1.02. There are only the version 1.00 soo you hare to fix please. Second things the cheats for final fantasy x /x-2 doesn't start they appear only in the first menu when we can chose if X or X-2 and then when we chose the game they disappear and they say that the version of the game there are no cheats

**Comment by kmeps4** [comment]
This is not GoldHEN issue.. we don't support cheats.. yes GoldHEN has a cheat engine but we're not cheat developers.. please submit these bugs with PS4 Trainer team.. gonna close cuz it's not directly related to GoldHEN

**Comment by kmeps4** [comment]
Here's the link of the GoldHEN Readme https://github.com/GoldHEN/GoldHEN#readme Please read the warning in full about the cheat menu... second this is the PS4Trainer Team Discord: https://discord.gg/7JrYmn6M... almost a 80% of json cheats were submitted by them!!!
