### ISSUE TITLE
Fallos menores entre goldhen y GoldHEN Cheat Manager 

### ISSUE THREAD

**Issue by bombardeo38** [GoldHEN/GoldHEN#81]
En la versión anterior si reconocía todas las versiones de los juegos que traen integrada la update pero hoy me dio por actualizar la lista de cheats y cuando entras en el apartado de cheats hd me di cuenta que el valhalla y el batman que son los que la tienen no aparece la estrella al lado pero luego si que funciona por lo menos en el valhalla

**Comment by kmeps4** [comment]
Ok.. first try to report on English.. second... can you explain better please.. it's a cheat.. GoldHEN cheat manager or GoldHEN itself.. also which CUSA you talking about and which GoldHEN version

**Comment by bombardeo38** [comment]
haber si me explico hay alguna incompatibilidad entre gold hen y goldhen cheats manager puesto que en la versión anterior sí que aparecen juegos con la estrella en el menú goldhen cheats manager cusa18534 v 5.10 integrada pero en el menú no aparece la estrella como que el juego tiene cheats es un ejemplo hay más como el minecraft juego basé sin actualizar que lo reconoce como una versión superior el cusa 00265 v1.00 la reconoce como 1.02 gracias

**Comment by kmeps4** [comment]
Don't worry.. ok.. GodHEN 2.2.4 has an improvement on the game version check.. gonna explain.. some titles/games got released as remastered.. this means that for Example if I remaster a game the resulting PKG will be always v01.00 on the game information but the Cheat Menu will display the correct version of the game... in this case.. I'm gonna use the following example:
Let's say I have CUSA12345 and base is 1.00 and I remaster and backport with an update v05.00 so... the remaster PKG when you install it on system information will say that CUSA12345 is v01.00 but his real version is v05.00.. so in this case GoldHEN 2.2.4 with recognize the game (Cheat Menu) as his real version v05.00, so if you don't have a Cheat for CUSA12345 v05.00 it will not display any cheat..... Now by other side we have the GoldHEN Cheat Manager so if I understand correctly the Cheat Manager is detecting the game version in the above example CUSA12345 as still v01.00 and not v05.00??? I think that's that issue you gonna try to explain?

**Comment by kmeps4** [comment]
If this is the case I'm gonna transfer this to Bucanero

**Comment by RandQalan** [comment]
> If this is the case I'm gonna transfer this to Bucanero

Take with your wisdom because he closed a lot if issues with out proper explanation or fix and not really dev behind this!

**Comment by bucanero** [comment]
> > If this is the case I'm gonna transfer this to Bucanero
> 
> Take with your wisdom because he closed a lot if issues with out proper explanation or fix and not really dev behind this!

Show which issue I closed without a proper explanation, or apologize right now.

**Comment by RandQalan** [comment]
> > > If this is the case I'm gonna transfer this to Bucanero
> > 
> > 
> > Take with your wisdom because he closed a lot if issues with out proper explanation or fix and not really dev behind this!
> 
> Show which issue I closed without a proper explanation, or apologize right now.

Not you Kameleon did closed a lot of issues and nothing but expaning of no GH but a lot of them nit related to cheat codes is GH issues. A lazy and dumb explanation.

**Comment by kmeps4** [comment]
I'm here shoot... report it again.. I need evidence.. send me klog of your "issue"... so I can verify when I have FREE TIME or Sistro to check it... do not go report NOT VALID ISSUES over GoldHEN please... this is pretty much a warning!!!

**Comment by kmeps4** [comment]
> > > If this is the case I'm gonna transfer this to Bucanero
> > 
> > 
> > Take with your wisdom because he closed a lot if issues with out proper explanation or fix and not really dev behind this!
> 
> Show which issue I closed without a proper explanation, or apologize right now.

@bucanero I'm gonna DM you and explain it better... it's not actually a Bug... but this dude over here creating drama

**Comment by RandQalan** [comment]
Really since 2.1 of Gh and a lot of report besides me. Check it your self. Your warning means nothing to me! Yeah drama like 20 email from closed isues with out fix. And stated I Spam you who is full of it. Ok I really will make this a cause why are you even responding to SiSTRo repo. You are not him!

I have been patient for a fix for DQW 1 since 2.0b2 after but always told NGHP. It is since GH 2.1 was broken and my report besides others have been closed without at least saying it can be fixed because. That tells me you don't know or at least don't can't give a response that is accurate. It is broken and is A GH 2.1 and above problem most likely cause is disable of Memory manager for cheat aboslute memory. Could be fixed by disabled of KLog on boot or a patch ti disable anti cheat. 

But instead of a proper answer your desided to blame others for this problem. I am telling you it's not others it's GH! 2.1 above. Hell GH 2.0b and 2.0b2 proves this.🤣

**Comment by kmeps4** [comment]
Ok lets go step by step (first losing time with you it's not worth) second...your "bugs" reported by any other user??? IF yes please attach links over here.
@SiSTR0 I'll keep following up this "smart" dude but I already warned him about a ban due to lot of spamming and insulting to me... so you tell me if I continue or ban this guy. thx in advance

**Comment by kmeps4** [comment]
@bombardeo38 por esta vez voy a hacer una excepción.. y voy a dar soporte en español.. se a lo que te refieres con las diferencias de versiones entre el GoldHEN 2.2.4 y el Cheat Manager... en la version 2.2.2 no se aplica el fix de la version correcta del juego en cambio en la version 2.2.4 si... puede ser que hayan algunas diferencias en el GoldHEN Manager pero voy a verificar este reporte lo mas pronto posible.

**Comment by kmeps4** [comment]
Ahora voy a proceder a cerrar este hilo ya que conocemos la situación.. si esta misma puede ser replicada u solventada te lo haremos saber por acá mismo. lo cierro porque no es un defecto directo de GoldHEN sino algo de sincronización que ocupa ser confirmado. Gracias por el reporte.

**Comment by bombardeo38** [comment]
not what I mean that it recognizes more version than it has installed in case of minecraft and in the menu of gold hen cheats manager now it does not appear in case of valhalla marked with the star but if I give the shader button if the cheats appear then there is cheat problems that are not activated in other games such as just cause 3 that infinite life and does not recharge even if you enable it by pressing the shader button it does not activate if you use the previous version of gold hen everything works thanks and sorry my translation

**Comment by bombardeo38** [comment]
![20220920_132738](https://user-images.githubusercontent.com/92440196/191246405-fcc754ef-6b33-441c-9e5f-a397aac46857.jpg)
![20220920_132639](https://user-images.githubusercontent.com/92440196/191246410-ad0ac29b-5456-4777-b7fe-2f30b77af021.jpg)
![20220920_132524](https://user-images.githubusercontent.com/92440196/191246417-606121eb-69a2-422c-a043-7a1e23d88c9a.jpg)
![20220920_132514](https://user-images.githubusercontent.com/92440196/191246423-e2dcb83b-f5f6-40fe-bc32-5c716b23662f.jpg)
Then, as I say, there are tricks that even if you activate them, they don't work. If I go back to 2.3b.2 or 2.2.2, they do work.
