### ISSUE TITLE
[Request] Psx Games Cheat Support

### ISSUE THREAD

**Issue by Scalerize** [GoldHEN/GoldHEN#82]
Don't know if it exists Yet,
but some people on Ps4Trainer discord are Requesting this feature.
If it already exists, Which i highly doubt, Then feel free to close this Request :D

**Comment by kmeps4** [comment]
Hello.
We're think on giving support to PS1 titles on cheat menu... we're researching the PS1 to GoldHEN port process to create a proper cheat parser
