### ISSUE TITLE
Problemas 

### ISSUE THREAD

**Issue by bombardeo38** [GoldHEN/GoldHEN#83]
Gracias de antemano Aber si me explico bien y no me tratan por tonto o alarmista te explico e descubierto que utilizando el último hen y el y el manager de los trucos el manager no reconoce que los juegos tienen truco no los marca con la estrella pero los juegos si que tienen si pulsas el boton share pero no se activan e encontrado estos en 3 juegos diferentes de esos famosos que no reconoce la versión el cusa 02747 v1.05 ,cusa18534 v 5.10 y cusa 00135 v1.14 qué tienes trucos pero no se activan a noser que utilice el trainer atraves del teléfono gracias otra vez y perdona las molestias

**Comment by kmeps4** [comment]
ya este reporte se esta viendo en el siguiente link: https://github.com/GoldHEN/GoldHEN_Cheat_Repository/issues/59
