### ISSUE TITLE
Goldhen 2.2.5b2 bug

### ISSUE THREAD

**Issue by StandVideo** [GoldHEN/GoldHEN#86]
Southbridge : unknown (0x0)

**Comment by StandVideo** [comment]
![Uploading CD690B34-CD84-4494-8E69-DB97F5F77F00.jpeg…]()

**Comment by StandVideo** [comment]
![4F4F3053-1F9B-423A-858E-68EE93F1B5CB](https://user-images.githubusercontent.com/99733463/193470568-e1f1842b-add4-44b1-ae49-8ce00e8aba6e.jpeg)

**Comment by kmeps4** [comment]
Hello. Thx for the report. it has been fixed for the next beta.
Thx a lot.
