### ISSUE TITLE
[Request] BluRay Disc Region change

### ISSUE THREAD

**Issue by barrywilcox** [GoldHEN/GoldHEN#87]
Other popular homebrew for ps3  (webman mod) would allow us to change the ps3 region from A, B , C to watch movies from any country.
This feature is very popular for ps3 and it would be amazing to see it brought to the ps4.

If there is a way to do this I would love to know how or see it added to goldHen thank you very much.

**Comment by kmeps4** [comment]
@SiSTR0 since this is a Request I'm going to close it but you can continue the thread!!!

**Comment by barrywilcox** [comment]
> @SiSTR0 since this is a Request I'm going to close it but you can continue the thread!!!

Ok thank you, do you know if there is a way to change the region of the BD-player on the Ps4 using any homebrew methods? The ps3 did have that option and I'm curious if any pros like yourself might know if its possible.

**Comment by SiSTR0** [comment]
Hi @barrywilcox, never try it. Do you have an error? can you get some klog when you get error? maybe we can do something but need details ;)
