### ISSUE TITLE
GoldHEN cheats version choosing

### ISSUE THREAD

**Issue by Reborn0100110** [GoldHEN/GoldHEN#90]
Is there a way to choose which version of cheat to use? If not is it possible to add that feature, I'm currently playing Far Cry 6 v1.06 and there's 3 version of cheats for v1.06 and it only chooses the first one. I was planning to use the second version.

**Comment by a44nonymous** [comment]
Please also let choose cheats from all supported formats (json, mc4, ...) at the same time.

Bonus: A lot of FPKG games are 1.0 even if they are a higher remastered version. Let choose cheats for another update version. Goldhen could also try to read the version history (not always accurate).

**Comment by Scalerize** [comment]
@kmeps4 This can be closed since it was added in recent Goldhen beta.
