### ISSUE TITLE
[REQUEST] Keep FTP server settings with network disabled

### ISSUE THREAD

**Issue by a44nonymous** [GoldHEN/GoldHEN#91]
FTP server can only be activated when a valid IP is found. The problem is once the FTP server fails to start once (no IP), the FTP server setting in Goldhen is turned off and has to be manually turned on the next time Goldhen is run..

Requested new behaviour: Every time Goldhen is run, try to start the FTP server even if it failed last time (as long as the Goldhen FTP server option was set by the user). Why?: Because I  keep the PS4 wifi connection off, but every time I turn it on I also want the FTP server on without having to activate it manually.

It should be very easy to make Goldhen remember the server settings, so when goldhen is run it will always try to load the FTP server.  It could also be added some extra feature like loading the FTP server if a network connection becomes available AFTER Goldhen is run.

**Comment by SiSTR0** [comment]
This feature was added in version v2.4b18
